default:
  consumer_key: "WCb6Z3Nwn7hGnhIbruprzRvyV"
  consumer_secret: "phffyAJ4ARjMxRiOT7YmQXHWYArZa0UiHQGL2vIKeKC7QUN7PJ"
  access_token: "1455545152362135574-kdLwJdv8nDVfbvZv8VmInqoLMSlg2V"
  access_secret: "0meMtledzMmxyCeWmzqGMqIMbR2ppSIeTwK5glCLNVCT8"
